Blog/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor',include('ckeditor_uploader.urls')),
    path('',include('Post.urls',namespace="Post")),
    path('accounts/',include('accounts.urls',namespace="accounts")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Post/urls.py
from django.contrib import admin
from django.urls import path , include
from .views import home, detail_article ,add_comment , add_reply , search


app_name = "Post"

urlpatterns = [
    path('',home,name="home"),
    path('article/<int:year>/<int:month>/<int:day>/<int:id>/<slug:slug>/',detail_article,name="detail_article"),
    path('article/<int:pk>/comment/',add_comment , name="add_comment"),
    path('article/comment/reply/<int:post_pk>/<int:comment_pk>/',add_reply , name="add_reply"),
    path('article/search/',search , name="search")
]

accounts/urls.py
from django.urls import path

app_name = "accounts"
urlpatterns = [
    
]

Post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from django.urls import reverse


class Post(models.Model):

    STATUS = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )

    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique_for_date='publish')
    body = RichTextUploadingField(config_name = "Post")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    publish = models.DateTimeField(default=timezone.now)
    status = models.CharField(choices=STATUS, max_length=10, default='draft')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse("Post:detail_article", args=[self.publish.year,self.publish.month,self.publish.day,self.id , self.slug])
    


    
class Comment(models.Model):
    post = models.ForeignKey(Post , on_delete=models.CASCADE , related_name="comments" , null = True , blank = True )
    reply = models.ForeignKey('self' , on_delete=models.CASCADE , related_name="rcomment" , null = True , blank = True )
    author = models.CharField(max_length=200)
    email = models.EmailField()
    body = models.TextField()                             
    created = models.DateTimeField(auto_now_add=True)

    class Meta :
        ordering = ('-created',)

    def __str__(self):
        return self.body[:30]
    

accounts/models.py
from django.db import models

# Create your models here.

Post/forms.py
from django import forms
from .models import Comment
from ckeditor.widgets import CKEditorWidget


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body','author','email')
        widgets = {
            'author': forms.TextInput(attrs={'class': 'answerForm__name' , 'placeholder':'name' }),
            'email': forms.EmailInput(attrs={'class': 'answerForm__email' , 'placeholder':'email'}),
            'body': forms.Textarea(attrs={'class': 'answerForm__body' , 'placeholder':'Message....'}),
        }

Post/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from django.http import HttpResponse
from django.contrib import messages
from .models import Post , Comment
from .forms import CommentForm



def home(request):
    contents = Post.objects.all()
    context = {
        "contents":contents,
    }
    return render(request,'Content.html',context)


def detail_article(request ,year , month , day , id , slug):
    article = get_object_or_404(Post,publish__year=year , publish__month=month , publish__day=day , pk=id , slug = slug)
    context = {
        "article":article,
        'myform':CommentForm,
    }

    return render(request ,'FullContent.html',context)


def add_comment(request , pk):
    post = get_object_or_404(Post , pk=pk)

    if request.method=='POST':
        name = request.POST.get("author")
        email = request.POST.get("email")
        body = request.POST.get("body")
        Comment(author=name , email=email , body = body , post=post).save()
        messages.success(request , "دیدگاه شما با موفقیت ثبت شد" )
        return redirect(post)


def add_reply(request , post_pk , comment_pk):
    comment = get_object_or_404(Comment , pk=comment_pk)
    post = get_object_or_404(Post , pk=post_pk)

    if request.method=='POST':
        name = request.POST.get("author")
        email = request.POST.get("email")
        body = request.POST.get("body")
        Comment(author=name , email=email , body = body , reply=comment).save()
        messages.success(request , "دیدگاه شما با موفقیت ثبت شد" )
        return redirect(post)

def search(request):
    search = request.GET.get('q')
    contents = Post.objects.filter(title__contains = search)
    context = {
        "contents":contents,
    }
    return render(request,'Content.html',context)
        
    

accounts/views.py
from django.shortcuts import render

# Create your views here.

Post/templates/Comment.html
{% for comment in article.comments.all %}

<div class="col-10">
    <div class="comment__box">
        <div class="comment__box--header">
            <div class="userAvatar">
                <img src="https://i.picsum.photos/id/890/200/300.jpg?hmac=INUR_Xore_GSEXH-cqmLjy_lJcK8tslVvXwwac-9o8M"
                    alt="">
            </div>
            <h4>{{ comment.author }}</h4>
            <p>تاریخ : <span>{{ comment.created|date:"SHORT_DATE_FORMAT" }}</span></p>
        </div>
        <div class="comment__box--content">
            <p>{{ comment.body }}</p>
        </div>
        <div class="comment__box--footer tempFooter">
            <button class="btn btn-dark send_comment">پاسخ</button>
        </div>
        <form action="{% url 'Post:add_reply' article.id  comment.id %}"  method="POST"  class="answerForm"> 
            {% csrf_token %}
            {{ myform.body}}
            <div class="answerForm__inputs">
                {{ myform.author}}
                {{ myform.email}}
            </div>
            <button class="btn btn-primary">Send</button>
        </form>
        {% include 'Reply.html' %}
    </div>
</div>
{% empty %}
    <p class="text-right">هیچ دیدگاهی وجود ندارد</p>
{% endfor %}

Post/templates/Content.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    {% for content in contents  %}
        <div class="col-10">
            <div class="row">
                <div class="content__Box">
                    <!-- Content Title -->
                    <h1>{{ content.title }}</h1>
                    <div class="content__header">

                        
                        <div class="content__header--text">
                            <p>
                            {{ content.body|safe }}
                            </p>
                        </div>
                    </div>
                    <!-- 0311310333412 -->
                    <!-- Content Information -->
                    <div class="content__footer">
                        <div class="content__footer--information">
                            <p>نویسنده : <span>{{ content.author.username }}</span></p>
                            <p>تاریخ : <span>{{ content.publish|date:"SHORT_DATE_FORMAT" }}</span> </p>
                        </div>
                        <span class="content__footer--goToContinue">
                            <a href="{{ content.get_absolute_url }}">
                                <i class="fas fa-angle-down"></i>
                            </a>
                        </span>
                        <span id="likeButton" class="content__footer--likeButton">
                            <i class="fas fa-heart">
                                <!-- <span class="likeButtonCount">0</span> -->
                            </i>
                        </span>

                    </div>

                </div>
            </div>
        </div>
    {% endfor %}
{% endblock content %}

Post/templates/FullContent.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<div class="col-10">
    <div class="row">
        <div class="content__Box">
            <!-- Content Title -->
            <h1>{{ article.title }}</h1>
            <div class="content__header">

                <div class="content__header--text">
                    <p>
                        {{ article.body |safe}}
                    </p>
                </div>
            </div>
            <!-- 0311310333412 -->
            <!-- Content Information -->
            <div class="content__footer">
                <div class="content__footer--information">
                    <p>نویسنده </br><span>{{ article.author }}</span></p>
                    <p>تاریخ </br><span>{{ article.publish|date:"SHORT_DATE_FORMAT" }}</span> </p>
                </div>
                <span id="likeButton" class="content__footer--likeButton">
                    <i class="fas fa-heart">
                        <!-- <span class="likeButtonCount">0</span> -->
                    </i>
                </span>

            </div>

        </div>
    </div>
</div>

<div class="commentToggle">
    دیدگاه ها
</div>

<section class="comment">
    <form action="{% url 'Post:add_comment' article.id %}"  method="POST"    class="commenting"> 
        {% csrf_token %}
        {{ myform.body}}
        <div class="answerForm__inputs">
            {{ myform.author}}
            {{ myform.email}}
        </div>
            <button class="btn btn-primary">Send</button>
    </form>
    {% include 'Comment.html' %}
</section>

{% endblock content %}

Post/templates/Reply.html
{% if comment.rcomment.all %}
    {% for comment in comment.rcomment.all %}

    <div class="comment__box--reply">
        <div class="comment__box--reply_header">
            <div class="userAvatar">
                <img src="https://i.picsum.photos/id/890/200/300.jpg?hmac=INUR_Xore_GSEXH-cqmLjy_lJcK8tslVvXwwac-9o8M"
                    alt="">
            </div>
            <h4>{{ comment.author }}</h4>
            <p>تاریخ : <span>{{ comment.created|date:"SHORT_DATE_FORMAT" }}</span></p>
        </div>
        <div class="comment__box--reply_content">
            <p>{{ comment.body }}</p>
        </div>
        <div class="comment__box--reply_footer tempFooter">
            <button class="btn btn-dark send_comment">پاسخ</button>
        </div>
        <form action="{% url 'Post:add_reply' article.id  comment.id %}"  method="POST" class="answerForm"> 
            {% csrf_token %}
            {{ myform.body}}
            <div class="answerForm__inputs">
                {{ myform.author}}
                {{ myform.email}}
            </div>
            <button class="btn btn-primary">Send</button>
        </form>
        {% include 'Reply.html' %}
    </div>

    {% endfor %}
{% endif %}

templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>

<html>

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/Style.css' %}" />

</head>

<body>


    <!-- TopHeader.html  -->
    {% include "include/TopHeader.html" %}

    <div class="container">
        <div class="row">
            <main>

                <!-- Header.html  -->
                {% include "include/Header.html" %}
              

                <!-- navbar.html  -->
                {% include "include/NavBar.html" %}
                {% include "include/messages.html" %}
                
            
                <section class="content">
                    <!-- Content.html -->
                    <!-- FullContent.html -->
                    {% block content %}
                    {% endblock content %}
                </section>



                <!-- footer.html -->
                {% include "include/Footer.html" %}
            </main>
        </div>
    </div>

    <!-- Preprocess js files -->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

    <!-- JS Part -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/include/Footer.html
<footer id="footer">
    <div class="footer">
        <h1>Copyright © 2021</h1>
    </div>
</footer>

templates/include/Header.html
<section class="header">
    <!-- Title -->
    <h1>Lorem Ipsum</h1>
    <!-- Description -->
    <p>لورم ایپسوم</p>
</section>

templates/include/NavBar.html
<nav class="navbar">
    <div class="hamburger">
        <div class="line"></div>
        <div class="line"></div>
        <div class="line"></div>
    </div>
    <ul class="navList">
        <li class="navChilds active">
            <a href="{% url 'Post:home' %}">خانه</a>
        </li>
        <li class="navChilds"><a href="#">درباره ما</a></li>
        <li class="navChilds">
            <a href="#">ارتباط با ما</a>
        </li>
        <li class="navChilds">
            <a href="#">تست</a>
        </li>
        <li class="navChilds">
            <a href="#">تست</a>
        </li>
    </ul>
    <div class="searchBox">
        <form action="{% url 'Post:search' %}" class="searchForm">
            <input type="search" id="q" name="q"> 
            <button type="submit" style="display: none">
                asd
            </button>
        </form>

        <i class="fas fa-search"></i>
    </div>
</nav>

templates/include/TopHeader.html
<section id="topHeader">
    <div class="container">
        <div class="row">
            <div class="topHeader">
                <div class="topHeader__right">
                    <ul>
                        <li>
                            <a href="#">ثبت نام <i class="fas fa-user-plus"></i></a>
                        </li>
                        <div class="loginContainer">
                            <li class="login">
                                <a href="#">ورود<i class="fas fa-sign-in-alt"></i></a>
                            </li>
                            <!-- Slide login form -->
                            <form action="" class="loginForm">
                                <input class="userInput" type="text" placeholder="نام کاربری" />
                                <input class="passInput" type="password" placeholder="کلمه عبور" />
                                <button class="btn btn-dark loginBtn" onclick="e.preventdefault()" type="submit">
                                    ورود
                                </button>
                            </form>
                        </div>
                    </ul>
                </div>
                <!-- Insta and etc icons -->
                <div class="topHeader__left">
                    <div class="icons">
                        <span class="instagram"><a href=""><i class="fab fa-instagram"></i></a></span>
                        <span class="telegram">
                            <a href=""><i class="fab fa-telegram"></i></a>
                        </span>
                        <span class="facebook">
                            <a href="">
                                <i class="fab fa-facebook"></i>
                            </a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/include/messages.html
{% if messages %}
    {% for message in messages  %}
        <div class="alert alert-{{ message.tags }} text-right" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}